version: '3'

services:
  database:
    container_name: postgres_database
    image: postgres:15beta2
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=postgres
    command: "python run.py"
    healthcheck:
      test: [CMD curl -f http://localhost/ || exit 1]
      timeout: 30s
      interval: 5m
    volumes:
      - .:/app



  apiflask-first:
    build: .
    hostname: apiflask_first
    ports:
      - '5000:5000'
    command: "python run.py"
    healthcheck:
      test: [ CMD curl -f http://localhost/ || exit 1 ]
      timeout: 30s
      interval: 5m
    volumes:
      - .:/app
    depends_on:
      - database



